name: Run ETL Pipeline Every 12 Hours

on:
  schedule:
    - cron: '0 6,18 * * *'  # Runs every 12 hours (at minute 0); '0 4 * * 1,5'

  # Optionally you can also run it manually
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest  # You can change this to `windows-latest` or `macos-latest` if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python load_pipe.py
